default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  schema_search_path: "public,shared_extensions"
  username: postgres
  password: "123456"



development: &development
  <<: *default
  database: consul_development

staging:
  <<: *development

preproduction:
  <<: *development

production:
  url: postgresql://lappadmin:Zwf1pfnyBethk5LMt1PuDEl26qBE5hIY@dpg-d1k9uth5pdvs73ai5e0g-a.oregon-postgres.render.com/laapp_production

test:
  <<: *default
  database: consul_test

